/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.alphasystem;

import org.junit.jupiter.api.Test;

import static com.alphasystem.StringOperations.findShortestSubstring;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

class StringOperationsTest {

    private static final Character[] DEFAULT_CHARS = {'b', 'c', 'd'};

    @Test
    void nonEmptyResultTest() {
        assertEquals("baadac", findShortestSubstring("aabaacaabaadacaa", DEFAULT_CHARS));
        assertEquals("bacacaaad", findShortestSubstring("dabaaaabacacaaadaaaa", DEFAULT_CHARS));
        assertEquals("cdb", findShortestSubstring("aabaacaabaadacdbaa", DEFAULT_CHARS));
        assertEquals("cdb", findShortestSubstring("aabaacaabaadacdbd", DEFAULT_CHARS));
    }

    @Test
    void noMatchTest() {
        assertNull(findShortestSubstring("xyzrgtj", DEFAULT_CHARS),
                "String does not have any matching characters");
    }

    @Test
    void exactMatchTest() {
        assertEquals("dbc", findShortestSubstring("dbc", DEFAULT_CHARS));
    }

}
